table CloudFlows
	lineageTag: 11111111-1111-1111-1111-111111111111

	column FlowID
		dataType: string
		summarizeBy: none
		sourceColumn: FlowID
		lineageTag: 11111111-1111-1111-1111-100000000001

	column FlowName
		dataType: string
		summarizeBy: none
		sourceColumn: FlowName
		lineageTag: 11111111-1111-1111-1111-100000000002

	column FlowDescription
		dataType: string
		summarizeBy: none
		sourceColumn: FlowDescription
		lineageTag: 11111111-1111-1111-1111-100000000003

	column StateCode
		dataType: int64
		summarizeBy: none
		sourceColumn: StateCode
		lineageTag: 11111111-1111-1111-1111-100000000004

	column StatusCode
		dataType: int64
		summarizeBy: none
		sourceColumn: StatusCode
		lineageTag: 11111111-1111-1111-1111-100000000005

	column OwnerID
		dataType: string
		summarizeBy: none
		sourceColumn: OwnerID
		lineageTag: 11111111-1111-1111-1111-100000000006

	column CreatedOn
		dataType: dateTime
		summarizeBy: none
		sourceColumn: CreatedOn
		lineageTag: 11111111-1111-1111-1111-100000000007

	column ModifiedOn
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ModifiedOn
		lineageTag: 11111111-1111-1111-1111-100000000008

	column PrimaryEntity
		dataType: string
		summarizeBy: none
		sourceColumn: PrimaryEntity
		lineageTag: 11111111-1111-1111-1111-100000000009

	column ClientData
		dataType: string
		summarizeBy: none
		sourceColumn: ClientData
		lineageTag: 11111111-1111-1111-1111-10000000000a

	column SolutionID
		dataType: string
		summarizeBy: none
		sourceColumn: SolutionID
		lineageTag: 11111111-1111-1111-1111-10000000000b

	column FlowState
		dataType: string
		summarizeBy: none
		sourceColumn: FlowState
		lineageTag: 11111111-1111-1111-1111-10000000000c

	column FlowStatus
		dataType: string
		summarizeBy: none
		sourceColumn: FlowStatus
		lineageTag: 11111111-1111-1111-1111-10000000000d

	column TriggerType
		dataType: string
		summarizeBy: none
		sourceColumn: TriggerType
		lineageTag: 11111111-1111-1111-1111-10000000000e

	column EnvironmentURL
		dataType: string
		summarizeBy: none
		sourceColumn: EnvironmentURL
		lineageTag: 11111111-1111-1111-1111-10000000000f

	column IsInSolution
		dataType: boolean
		summarizeBy: none
		sourceColumn: IsInSolution
		lineageTag: 11111111-1111-1111-1111-100000000010

	partition CloudFlows = m
		mode: import
		source =
			let
			    Source = OData.Feed(
			        #"BaseURL" & "workflows?$filter=category eq 5 and type eq 1"
			            & "&$select=workflowid,name,description,category,statecode,statuscode,"
			            & "_ownerid_value,createdon,modifiedon,primaryentity,clientdata,solutionid",
			        null,
			        [Implementation = "2.0", ODataVersion = 4]
			    ),
			    RenamedColumns = Table.RenameColumns(Source, {
			        {"workflowid", "FlowID"}, {"name", "FlowName"},
			        {"description", "FlowDescription"}, {"statecode", "StateCode"},
			        {"statuscode", "StatusCode"}, {"_ownerid_value", "OwnerID"},
			        {"createdon", "CreatedOn"}, {"modifiedon", "ModifiedOn"},
			        {"primaryentity", "PrimaryEntity"}, {"clientdata", "ClientData"},
			        {"solutionid", "SolutionID"}
			    }, MissingField.Ignore),
			    AddStateName = Table.AddColumn(RenamedColumns, "FlowState", each
			        if [StateCode] = 0 then "Draft"
			        else if [StateCode] = 1 then "Activated"
			        else if [StateCode] = 2 then "Suspended"
			        else "Unknown", type text),
			    AddStatusName = Table.AddColumn(AddStateName, "FlowStatus", each
			        if [StatusCode] = 1 then "Draft"
			        else if [StatusCode] = 2 then "Activated"
			        else "Other", type text),
			    AddTriggerType = Table.AddColumn(AddStatusName, "TriggerType", each
			        try let jsonData = Json.Document([ClientData]),
			            properties = jsonData[properties], definition = properties[definition],
			            triggers = Record.FieldNames(definition[triggers])
			        in triggers{0} otherwise "Unknown", type text),
			    AddEnvironment = Table.AddColumn(AddTriggerType, "EnvironmentURL", each #"EnvironmentURL", type text),
			    AddSolutionFlag = Table.AddColumn(AddEnvironment, "IsInSolution", each
			        try ([SolutionID] <> null and [SolutionID] <> "00000000-0000-0000-0000-000000000000") otherwise false, type logical)
			in
			    AddSolutionFlag
