{
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "CloudFlows",
        "columns": [
          { "name": "FlowID", "dataType": "string", "sourceColumn": "FlowID", "summarizeBy": "none" },
          { "name": "FlowName", "dataType": "string", "sourceColumn": "FlowName", "summarizeBy": "none" },
          { "name": "FlowDescription", "dataType": "string", "sourceColumn": "FlowDescription", "summarizeBy": "none" },
          { "name": "StateCode", "dataType": "int64", "sourceColumn": "StateCode", "summarizeBy": "none" },
          { "name": "StatusCode", "dataType": "int64", "sourceColumn": "StatusCode", "summarizeBy": "none" },
          { "name": "OwnerID", "dataType": "string", "sourceColumn": "OwnerID", "summarizeBy": "none" },
          { "name": "CreatedOn", "dataType": "dateTime", "sourceColumn": "CreatedOn", "summarizeBy": "none" },
          { "name": "ModifiedOn", "dataType": "dateTime", "sourceColumn": "ModifiedOn", "summarizeBy": "none" },
          { "name": "PrimaryEntity", "dataType": "string", "sourceColumn": "PrimaryEntity", "summarizeBy": "none" },
          { "name": "ClientData", "dataType": "string", "sourceColumn": "ClientData", "summarizeBy": "none" },
          { "name": "SolutionID", "dataType": "string", "sourceColumn": "SolutionID", "summarizeBy": "none" },
          { "name": "FlowState", "dataType": "string", "sourceColumn": "FlowState", "summarizeBy": "none" },
          { "name": "FlowStatus", "dataType": "string", "sourceColumn": "FlowStatus", "summarizeBy": "none" },
          { "name": "TriggerType", "dataType": "string", "sourceColumn": "TriggerType", "summarizeBy": "none" },
          { "name": "EnvironmentURL", "dataType": "string", "sourceColumn": "EnvironmentURL", "summarizeBy": "none" },
          { "name": "IsInSolution", "dataType": "boolean", "sourceColumn": "IsInSolution", "summarizeBy": "none" }
        ],
        "partitions": [
          {
            "name": "CloudFlows",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    EnvironmentURL = \"org0d734703.crm.dynamics.com\",",
                "    BaseURL = \"https://\" & EnvironmentURL & \"/api/data/v9.2/\",",
                "    Source = OData.Feed(",
                "        BaseURL & \"workflows?$filter=category eq 5 and type eq 1\"",
                "            & \"&$select=workflowid,name,description,category,statecode,statuscode,\"",
                "            & \"_ownerid_value,createdon,modifiedon,primaryentity,clientdata,solutionid\",",
                "        null,",
                "        [Implementation = \"2.0\", ODataVersion = 4]",
                "    ),",
                "    RenamedColumns = Table.RenameColumns(Source, {",
                "        {\"workflowid\", \"FlowID\"}, {\"name\", \"FlowName\"},",
                "        {\"description\", \"FlowDescription\"}, {\"statecode\", \"StateCode\"},",
                "        {\"statuscode\", \"StatusCode\"}, {\"_ownerid_value\", \"OwnerID\"},",
                "        {\"createdon\", \"CreatedOn\"}, {\"modifiedon\", \"ModifiedOn\"},",
                "        {\"primaryentity\", \"PrimaryEntity\"}, {\"clientdata\", \"ClientData\"},",
                "        {\"solutionid\", \"SolutionID\"}",
                "    }, MissingField.Ignore),",
                "    AddStateName = Table.AddColumn(RenamedColumns, \"FlowState\", each",
                "        if [StateCode] = 0 then \"Draft\"",
                "        else if [StateCode] = 1 then \"Activated\"",
                "        else if [StateCode] = 2 then \"Suspended\"",
                "        else \"Unknown\", type text),",
                "    AddStatusName = Table.AddColumn(AddStateName, \"FlowStatus\", each",
                "        if [StatusCode] = 1 then \"Draft\"",
                "        else if [StatusCode] = 2 then \"Activated\"",
                "        else \"Other\", type text),",
                "    AddTriggerType = Table.AddColumn(AddStatusName, \"TriggerType\", each",
                "        try let jsonData = Json.Document([ClientData]),",
                "            properties = jsonData[properties], definition = properties[definition],",
                "            triggers = Record.FieldNames(definition[triggers])",
                "        in triggers{0} otherwise \"Unknown\", type text),",
                "    AddEnvironment = Table.AddColumn(AddTriggerType, \"EnvironmentURL\", each EnvironmentURL, type text),",
                "    AddSolutionFlag = Table.AddColumn(AddEnvironment, \"IsInSolution\", each",
                "        try ([SolutionID] <> null and [SolutionID] <> \"00000000-0000-0000-0000-000000000000\") otherwise false, type logical)",
                "in",
                "    AddSolutionFlag"
              ]
            }
          }
        ]
      },
      {
        "name": "FlowRuns",
        "columns": [
          { "name": "RunID", "dataType": "string", "sourceColumn": "RunID", "summarizeBy": "none" },
          { "name": "RunName", "dataType": "string", "sourceColumn": "RunName", "summarizeBy": "none" },
          { "name": "FlowID", "dataType": "string", "sourceColumn": "FlowID", "summarizeBy": "none" },
          { "name": "RunStatusCode", "dataType": "int64", "sourceColumn": "RunStatusCode", "summarizeBy": "none" },
          { "name": "RunStateCode", "dataType": "int64", "sourceColumn": "RunStateCode", "summarizeBy": "none" },
          { "name": "StartedOn", "dataType": "dateTime", "sourceColumn": "StartedOn", "summarizeBy": "none" },
          { "name": "CompletedOn", "dataType": "dateTime", "sourceColumn": "CompletedOn", "summarizeBy": "none" },
          { "name": "ErrorCode", "dataType": "string", "sourceColumn": "ErrorCode", "summarizeBy": "none" },
          { "name": "ErrorMessage", "dataType": "string", "sourceColumn": "ErrorMessage", "summarizeBy": "none" },
          { "name": "CreatedOn", "dataType": "dateTime", "sourceColumn": "CreatedOn", "summarizeBy": "none" },
          { "name": "RunStatus", "dataType": "string", "sourceColumn": "RunStatus", "summarizeBy": "none" },
          { "name": "StatusCategory", "dataType": "string", "sourceColumn": "StatusCategory", "summarizeBy": "none" },
          { "name": "DurationSeconds", "dataType": "double", "sourceColumn": "DurationSeconds", "summarizeBy": "sum" },
          { "name": "DurationMinutes", "dataType": "double", "sourceColumn": "DurationMinutes", "summarizeBy": "sum" },
          { "name": "RunDate", "dataType": "dateTime", "sourceColumn": "RunDate", "summarizeBy": "none" },
          { "name": "RunHour", "dataType": "int64", "sourceColumn": "RunHour", "summarizeBy": "none" },
          { "name": "DayOfWeek", "dataType": "string", "sourceColumn": "DayOfWeek", "summarizeBy": "none" },
          { "name": "IsBusinessHours", "dataType": "boolean", "sourceColumn": "IsBusinessHours", "summarizeBy": "none" },
          { "name": "ErrorCategory", "dataType": "string", "sourceColumn": "ErrorCategory", "summarizeBy": "none" },
          { "name": "EnvironmentURL", "dataType": "string", "sourceColumn": "EnvironmentURL", "summarizeBy": "none" }
        ],
        "partitions": [
          {
            "name": "FlowRuns",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    EnvironmentURL = \"org0d734703.crm.dynamics.com\",",
                "    DaysToLoad = 90,",
                "    CutoffDate = DateTime.ToText(Date.AddDays(DateTime.LocalNow(), -DaysToLoad), \"yyyy-MM-ddTHH:mm:ssZ\"),",
                "    BaseURL = \"https://\" & EnvironmentURL & \"/api/data/v9.2/\",",
                "    Source = OData.Feed(",
                "        BaseURL & \"flowsessions?$filter=createdon ge \" & CutoffDate",
                "            & \"&$select=flowsessionid,name,_regardingobjectid_value,statuscode,\"",
                "            & \"statecode,startedon,completedon,errorcode,errormessage,createdon\",",
                "        null,",
                "        [Implementation = \"2.0\", ODataVersion = 4]",
                "    ),",
                "    RenamedColumns = Table.RenameColumns(Source, {",
                "        {\"flowsessionid\", \"RunID\"}, {\"name\", \"RunName\"},",
                "        {\"_regardingobjectid_value\", \"FlowID\"}, {\"statuscode\", \"RunStatusCode\"},",
                "        {\"statecode\", \"RunStateCode\"}, {\"startedon\", \"StartedOn\"},",
                "        {\"completedon\", \"CompletedOn\"}, {\"errorcode\", \"ErrorCode\"},",
                "        {\"errormessage\", \"ErrorMessage\"}, {\"createdon\", \"CreatedOn\"}",
                "    }, MissingField.Ignore),",
                "    AddRunStatus = Table.AddColumn(RenamedColumns, \"RunStatus\", each",
                "        if [RunStatusCode] = 4 then \"Succeeded\"",
                "        else if [RunStatusCode] = 8 then \"Failed\"",
                "        else if [RunStatusCode] = 9 then \"Faulted\"",
                "        else if [RunStatusCode] = 7 then \"Cancelled\"",
                "        else if [RunStatusCode] = 10 then \"TimedOut\"",
                "        else if [RunStatusCode] = 2 then \"Running\"",
                "        else if [RunStatusCode] = 3 then \"Waiting\"",
                "        else if [RunStatusCode] = 1 then \"Paused\"",
                "        else \"Other\", type text),",
                "    AddStatusCategory = Table.AddColumn(AddRunStatus, \"StatusCategory\", each",
                "        if [RunStatusCode] = 4 then \"Succeeded\"",
                "        else if [RunStatusCode] = 8 or [RunStatusCode] = 9 then \"Failed\"",
                "        else if [RunStatusCode] = 7 then \"Cancelled\"",
                "        else if [RunStatusCode] = 10 then \"Timed Out\"",
                "        else if [RunStatusCode] = 2 or [RunStatusCode] = 3 then \"In Progress\"",
                "        else \"Other\", type text),",
                "    AddDuration = Table.AddColumn(AddStatusCategory, \"DurationSeconds\", each",
                "        try Duration.TotalSeconds([CompletedOn] - [StartedOn]) otherwise null, type number),",
                "    AddDurationMinutes = Table.AddColumn(AddDuration, \"DurationMinutes\", each",
                "        try [DurationSeconds] / 60 otherwise null, type number),",
                "    AddRunDate = Table.AddColumn(AddDurationMinutes, \"RunDate\", each",
                "        try DateTime.Date(DateTime.From([StartedOn])) otherwise null, type date),",
                "    AddRunHour = Table.AddColumn(AddRunDate, \"RunHour\", each",
                "        try Time.Hour(DateTime.Time(DateTime.From([StartedOn]))) otherwise null, Int64.Type),",
                "    AddDayOfWeek = Table.AddColumn(AddRunHour, \"DayOfWeek\", each",
                "        try Date.DayOfWeekName([RunDate]) otherwise null, type text),",
                "    AddBusinessHours = Table.AddColumn(AddDayOfWeek, \"IsBusinessHours\", each",
                "        try let dow = Date.DayOfWeek([RunDate], Day.Monday), hour = [RunHour]",
                "        in (dow >= 0 and dow <= 4) and (hour >= 8 and hour < 18) otherwise null, type logical),",
                "    AddErrorCategory = Table.AddColumn(AddBusinessHours, \"ErrorCategory\", each",
                "        if [RunStatusCode] <> 8 and [RunStatusCode] <> 9 then null",
                "        else if [ErrorCode] = null or [ErrorCode] = \"\" then \"Uncategorized\"",
                "        else if Text.Contains(Text.Lower(Text.From([ErrorCode])), \"timeout\") then \"Timeout\"",
                "        else if Text.Contains(Text.Lower(Text.From([ErrorCode])), \"unauthorized\") then \"Authorization\"",
                "        else if Text.Contains(Text.Lower(Text.From([ErrorCode])), \"throttl\") then \"Throttled\"",
                "        else \"Other Error\", type text),",
                "    AddEnvironment = Table.AddColumn(AddErrorCategory, \"EnvironmentURL\", each EnvironmentURL, type text)",
                "in",
                "    AddEnvironment"
              ]
            }
          }
        ]
      },
      {
        "name": "SystemUsers",
        "columns": [
          { "name": "UserID", "dataType": "string", "sourceColumn": "UserID", "summarizeBy": "none" },
          { "name": "FullName", "dataType": "string", "sourceColumn": "FullName", "summarizeBy": "none" },
          { "name": "FirstName", "dataType": "string", "sourceColumn": "FirstName", "summarizeBy": "none" },
          { "name": "LastName", "dataType": "string", "sourceColumn": "LastName", "summarizeBy": "none" },
          { "name": "Email", "dataType": "string", "sourceColumn": "Email", "summarizeBy": "none" },
          { "name": "DomainName", "dataType": "string", "sourceColumn": "DomainName", "summarizeBy": "none" },
          { "name": "IsDisabled", "dataType": "boolean", "sourceColumn": "IsDisabled", "summarizeBy": "none" },
          { "name": "JobTitle", "dataType": "string", "sourceColumn": "JobTitle", "summarizeBy": "none" },
          { "name": "AzureADObjectID", "dataType": "string", "sourceColumn": "AzureADObjectID", "summarizeBy": "none" },
          { "name": "UserStatus", "dataType": "string", "sourceColumn": "UserStatus", "summarizeBy": "none" },
          { "name": "UserDisplayLabel", "dataType": "string", "sourceColumn": "UserDisplayLabel", "summarizeBy": "none" },
          { "name": "EnvironmentURL", "dataType": "string", "sourceColumn": "EnvironmentURL", "summarizeBy": "none" }
        ],
        "partitions": [
          {
            "name": "SystemUsers",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    EnvironmentURL = \"org0d734703.crm.dynamics.com\",",
                "    BaseURL = \"https://\" & EnvironmentURL & \"/api/data/v9.2/\",",
                "    Source = OData.Feed(",
                "        BaseURL & \"systemusers?$select=systemuserid,fullname,firstname,lastname,\"",
                "            & \"internalemailaddress,domainname,isdisabled,title,azureactivedirectoryobjectid\",",
                "        null,",
                "        [Implementation = \"2.0\", ODataVersion = 4]",
                "    ),",
                "    RenamedColumns = Table.RenameColumns(Source, {",
                "        {\"systemuserid\", \"UserID\"}, {\"fullname\", \"FullName\"},",
                "        {\"firstname\", \"FirstName\"}, {\"lastname\", \"LastName\"},",
                "        {\"internalemailaddress\", \"Email\"}, {\"domainname\", \"DomainName\"},",
                "        {\"isdisabled\", \"IsDisabled\"}, {\"title\", \"JobTitle\"},",
                "        {\"azureactivedirectoryobjectid\", \"AzureADObjectID\"}",
                "    }, MissingField.Ignore),",
                "    AddUserStatus = Table.AddColumn(RenamedColumns, \"UserStatus\", each",
                "        if [IsDisabled] = true then \"Disabled\" else \"Active\", type text),",
                "    AddDisplayLabel = Table.AddColumn(AddUserStatus, \"UserDisplayLabel\", each",
                "        let name = if [FullName] <> null and [FullName] <> \"\" then [FullName] else \"Unknown\",",
                "            email = if [Email] <> null and [Email] <> \"\" then \" (\" & [Email] & \")\" else \"\"",
                "        in name & email, type text),",
                "    AddEnvironment = Table.AddColumn(AddDisplayLabel, \"EnvironmentURL\", each EnvironmentURL, type text)",
                "in",
                "    AddEnvironment"
              ]
            }
          }
        ]
      },
      {
        "name": "ProcessConfiguration",
        "columns": [
          { "name": "FlowName", "dataType": "string", "sourceColumn": "FlowName", "summarizeBy": "none" },
          { "name": "BusinessProcess", "dataType": "string", "sourceColumn": "BusinessProcess", "summarizeBy": "none" },
          { "name": "ProcessCategory", "dataType": "string", "sourceColumn": "ProcessCategory", "summarizeBy": "none" },
          { "name": "Department", "dataType": "string", "sourceColumn": "Department", "summarizeBy": "none" },
          { "name": "MinutesSavedPerRun", "dataType": "double", "sourceColumn": "MinutesSavedPerRun", "summarizeBy": "sum" },
          { "name": "RiskCategory", "dataType": "string", "sourceColumn": "RiskCategory", "summarizeBy": "none" },
          { "name": "RiskReductionScore", "dataType": "int64", "sourceColumn": "RiskReductionScore", "summarizeBy": "sum" },
          { "name": "ProcessOwner", "dataType": "string", "sourceColumn": "ProcessOwner", "summarizeBy": "none" },
          { "name": "Notes", "dataType": "string", "sourceColumn": "Notes", "summarizeBy": "none" }
        ],
        "partitions": [
          {
            "name": "ProcessConfiguration",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords({",
                "        [FlowName = \"(Enter your flow name)\", BusinessProcess = \"(Enter process)\", ProcessCategory = \"General\", Department = \"General\", MinutesSavedPerRun = 15, RiskCategory = \"Medium\", RiskReductionScore = 5, ProcessOwner = \"owner@yourorg.com\", Notes = \"Sample row - replace with your data\"]",
                "    }),",
                "    TypedTable = Table.TransformColumnTypes(Source, {",
                "        {\"FlowName\", type text}, {\"BusinessProcess\", type text},",
                "        {\"ProcessCategory\", type text}, {\"Department\", type text},",
                "        {\"MinutesSavedPerRun\", type number}, {\"RiskCategory\", type text},",
                "        {\"RiskReductionScore\", Int64.Type}, {\"ProcessOwner\", type text},",
                "        {\"Notes\", type text}",
                "    })",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "DateTable",
        "columns": [
          { "name": "Date", "dataType": "dateTime", "sourceColumn": "Date", "summarizeBy": "none", "isKey": true },
          { "name": "Year", "dataType": "int64", "sourceColumn": "Year", "summarizeBy": "none" },
          { "name": "MonthNumber", "dataType": "int64", "sourceColumn": "MonthNumber", "summarizeBy": "none" },
          { "name": "MonthName", "dataType": "string", "sourceColumn": "MonthName", "summarizeBy": "none", "sortByColumn": "MonthNumber" },
          { "name": "MonthShort", "dataType": "string", "sourceColumn": "MonthShort", "summarizeBy": "none", "sortByColumn": "MonthNumber" },
          { "name": "Day", "dataType": "int64", "sourceColumn": "Day", "summarizeBy": "none" },
          { "name": "DayOfWeek", "dataType": "int64", "sourceColumn": "DayOfWeek", "summarizeBy": "none" },
          { "name": "DayName", "dataType": "string", "sourceColumn": "DayName", "summarizeBy": "none", "sortByColumn": "DayOfWeek" },
          { "name": "Quarter", "dataType": "int64", "sourceColumn": "Quarter", "summarizeBy": "none" },
          { "name": "QuarterLabel", "dataType": "string", "sourceColumn": "QuarterLabel", "summarizeBy": "none", "sortByColumn": "Quarter" },
          { "name": "YearMonth", "dataType": "string", "sourceColumn": "YearMonth", "summarizeBy": "none" },
          { "name": "YearQuarter", "dataType": "string", "sourceColumn": "YearQuarter", "summarizeBy": "none" },
          { "name": "IsWeekend", "dataType": "boolean", "sourceColumn": "IsWeekend", "summarizeBy": "none" },
          { "name": "FiscalYear", "dataType": "int64", "sourceColumn": "FiscalYear", "summarizeBy": "none" }
        ],
        "partitions": [
          {
            "name": "DateTable",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    StartDate = Date.StartOfYear(Date.AddYears(DateTime.Date(DateTime.LocalNow()), -2)),",
                "    EndDate = Date.EndOfYear(Date.AddYears(DateTime.Date(DateTime.LocalNow()), 1)),",
                "    DateCount = Duration.Days(EndDate - StartDate) + 1,",
                "    DateList = List.Dates(StartDate, DateCount, #duration(1, 0, 0, 0)),",
                "    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {\"Date\"}),",
                "    TypedDate = Table.TransformColumnTypes(DateTable, {{\"Date\", type date}}),",
                "    AddYear = Table.AddColumn(TypedDate, \"Year\", each Date.Year([Date]), Int64.Type),",
                "    AddMonth = Table.AddColumn(AddYear, \"MonthNumber\", each Date.Month([Date]), Int64.Type),",
                "    AddMonthName = Table.AddColumn(AddMonth, \"MonthName\", each Date.MonthName([Date]), type text),",
                "    AddMonthShort = Table.AddColumn(AddMonthName, \"MonthShort\", each Text.Start(Date.MonthName([Date]), 3), type text),",
                "    AddDay = Table.AddColumn(AddMonthShort, \"Day\", each Date.Day([Date]), Int64.Type),",
                "    AddDayOfWeek = Table.AddColumn(AddDay, \"DayOfWeek\", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),",
                "    AddDayName = Table.AddColumn(AddDayOfWeek, \"DayName\", each Date.DayOfWeekName([Date]), type text),",
                "    AddQuarter = Table.AddColumn(AddDayName, \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    AddQuarterLabel = Table.AddColumn(AddQuarter, \"QuarterLabel\", each \"Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    AddYearMonth = Table.AddColumn(AddQuarterLabel, \"YearMonth\", each Text.From(Date.Year([Date])) & \"-\" & Text.PadStart(Text.From(Date.Month([Date])), 2, \"0\"), type text),",
                "    AddYearQuarter = Table.AddColumn(AddYearMonth, \"YearQuarter\", each Text.From(Date.Year([Date])) & \" Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    AddIsWeekend = Table.AddColumn(AddYearQuarter, \"IsWeekend\", each Date.DayOfWeek([Date], Day.Monday) >= 5, type logical),",
                "    AddFiscalYear = Table.AddColumn(AddIsWeekend, \"FiscalYear\", each if Date.Month([Date]) >= 7 then Date.Year([Date]) + 1 else Date.Year([Date]), Int64.Type)",
                "in",
                "    AddFiscalYear"
              ]
            }
          }
        ],
        "annotations": [
          { "name": "__PBI_LocalDateTable", "value": "true" }
        ]
      },
      {
        "name": "_Measures",
        "columns": [
          { "name": "MeasureHelper", "dataType": "int64", "sourceColumn": "MeasureHelper", "isHidden": true, "summarizeBy": "none" }
        ],
        "measures": [
          {
            "name": "Total Environments",
            "expression": "DISTINCTCOUNT(CloudFlows[EnvironmentURL])",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Cloud Flows",
            "expression": "COUNTROWS(CloudFlows)",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Active Flows",
            "expression": "CALCULATE(COUNTROWS(CloudFlows), CloudFlows[FlowState] = \"Activated\")",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Draft Flows",
            "expression": "CALCULATE(COUNTROWS(CloudFlows), CloudFlows[FlowState] = \"Draft\")",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Suspended Flows",
            "expression": "CALCULATE(COUNTROWS(CloudFlows), CloudFlows[FlowState] = \"Suspended\")",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Active Flow Percentage",
            "expression": "DIVIDE([Total Active Flows], [Total Cloud Flows], 0)",
            "formatString": "0.0%",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Flows in Solutions",
            "expression": "CALCULATE(COUNTROWS(CloudFlows), CloudFlows[IsInSolution] = TRUE())",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Solution Coverage",
            "expression": "DIVIDE([Flows in Solutions], [Total Cloud Flows], 0)",
            "formatString": "0.0%",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Unique Flow Owners",
            "expression": "DISTINCTCOUNT(CloudFlows[OwnerID])",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Mapped Business Processes",
            "expression": "DISTINCTCOUNT(ProcessConfiguration[BusinessProcess])",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Flow Runs",
            "expression": "COUNTROWS(FlowRuns)",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Succeeded Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[StatusCategory] = \"Succeeded\")",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Failed Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[StatusCategory] = \"Failed\")",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Cancelled Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[StatusCategory] = \"Cancelled\")",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Timed Out Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[StatusCategory] = \"Timed Out\")",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Success Rate",
            "expression": "DIVIDE([Succeeded Runs], [Total Flow Runs], 0)",
            "formatString": "0.0%",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Failure Rate",
            "expression": "DIVIDE([Failed Runs], [Total Flow Runs], 0)",
            "formatString": "0.0%",
            "displayFolder": "Flow Runs"
          },
          {
            "name": "Avg Run Duration (Minutes)",
            "expression": "AVERAGE(FlowRuns[DurationMinutes])",
            "formatString": "0.0",
            "displayFolder": "Flow Runs\\Duration"
          },
          {
            "name": "Median Run Duration (Minutes)",
            "expression": "MEDIAN(FlowRuns[DurationMinutes])",
            "formatString": "0.0",
            "displayFolder": "Flow Runs\\Duration"
          },
          {
            "name": "P95 Run Duration (Minutes)",
            "expression": "PERCENTILE.INC(FlowRuns[DurationMinutes], 0.95)",
            "formatString": "0.0",
            "displayFolder": "Flow Runs\\Duration"
          },
          {
            "name": "Total Run Duration (Hours)",
            "expression": "DIVIDE(SUM(FlowRuns[DurationSeconds]), 3600, 0)",
            "formatString": "#,##0.0",
            "displayFolder": "Flow Runs\\Duration"
          },
          {
            "name": "Runs Last 30 Days",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), DATESINPERIOD(DateTable[Date], TODAY(), -30, DAY))",
            "displayFolder": "Flow Runs\\Trends"
          },
          {
            "name": "Business Hours Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[IsBusinessHours] = TRUE())",
            "displayFolder": "Flow Runs\\Trends"
          },
          {
            "name": "After Hours Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), FlowRuns[IsBusinessHours] = FALSE())",
            "displayFolder": "Flow Runs\\Trends"
          },
          {
            "name": "Daily Runs",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), LASTDATE(DateTable[Date]))",
            "displayFolder": "Flow Runs\\Trends"
          },
          {
            "name": "Rolling 7 Day Avg Runs",
            "expression": "AVERAGEX(DATESINPERIOD(DateTable[Date], MAX(DateTable[Date]), -7, DAY), [Daily Runs])",
            "formatString": "0.0",
            "displayFolder": "Flow Runs\\Trends"
          },
          {
            "name": "Total Minutes Saved",
            "expression": [
              "SUMX(",
              "    FlowRuns,",
              "    IF(",
              "        FlowRuns[StatusCategory] = \"Succeeded\",",
              "        VAR FlowName = LOOKUPVALUE(CloudFlows[FlowName], CloudFlows[FlowID], FlowRuns[FlowID])",
              "        VAR ConfigMinutes = LOOKUPVALUE(ProcessConfiguration[MinutesSavedPerRun], ProcessConfiguration[FlowName], FlowName)",
              "        RETURN IF(NOT ISBLANK(ConfigMinutes), ConfigMinutes, 15),",
              "        0",
              "    )",
              ")"
            ],
            "displayFolder": "Time Savings"
          },
          {
            "name": "Total Hours Saved",
            "expression": "DIVIDE([Total Minutes Saved], 60, 0)",
            "formatString": "#,##0.0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Total Days Saved",
            "expression": "DIVIDE([Total Hours Saved], 8, 0)",
            "formatString": "#,##0.0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Total FTE Equivalent",
            "expression": "DIVIDE([Total Hours Saved], 2080, 0)",
            "formatString": "0.00",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Estimated Cost Savings",
            "expression": "VAR HourlyCost = 50\nRETURN [Total Hours Saved] * HourlyCost",
            "formatString": "$#,##0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Monthly Cost Savings",
            "expression": "CALCULATE([Estimated Cost Savings], DATESMTD(DateTable[Date]))",
            "formatString": "$#,##0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Annual Cost Savings Projection",
            "expression": "[Monthly Cost Savings] * 12",
            "formatString": "$#,##0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Value Per Run",
            "expression": "DIVIDE([Estimated Cost Savings], [Succeeded Runs], 0)",
            "formatString": "$#,##0.00",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Cumulative Hours Saved",
            "expression": "CALCULATE([Total Hours Saved], FILTER(ALL(DateTable[Date]), DateTable[Date] <= MAX(DateTable[Date])))",
            "formatString": "#,##0.0",
            "displayFolder": "Time Savings"
          },
          {
            "name": "Risk Reduction Value",
            "expression": [
              "SUMX(",
              "    ProcessConfiguration,",
              "    VAR RiskScore = ProcessConfiguration[RiskReductionScore]",
              "    VAR RiskCategoryVal = SWITCH(ProcessConfiguration[RiskCategory],",
              "        \"Critical\", 10000, \"High\", 5000, \"Medium\", 1000, \"Low\", 200, 0)",
              "    VAR FlowName = ProcessConfiguration[FlowName]",
              "    VAR SuccessfulRuns = CALCULATE(COUNTROWS(FlowRuns),",
              "        FlowRuns[StatusCategory] = \"Succeeded\", CloudFlows[FlowName] = FlowName)",
              "    VAR ManualErrorProbability = 0.05",
              "    RETURN SuccessfulRuns * ManualErrorProbability * RiskCategoryVal * (RiskScore / 10)",
              ")"
            ],
            "formatString": "$#,##0",
            "displayFolder": "Risk"
          },
          {
            "name": "Monthly Risk Reduction Value",
            "expression": "CALCULATE([Risk Reduction Value], DATESMTD(DateTable[Date]))",
            "formatString": "$#,##0",
            "displayFolder": "Risk"
          },
          {
            "name": "Total Automation Value",
            "expression": "[Estimated Cost Savings] + [Risk Reduction Value]",
            "formatString": "$#,##0",
            "displayFolder": "Risk"
          },
          {
            "name": "High Risk Processes",
            "expression": "CALCULATE(COUNTROWS(ProcessConfiguration), ProcessConfiguration[RiskCategory] IN {\"High\", \"Critical\"})",
            "displayFolder": "Risk"
          },
          {
            "name": "Risk Reduction Achievement",
            "expression": [
              "VAR TotalScore = SUMX(ProcessConfiguration,",
              "    VAR RiskScore = ProcessConfiguration[RiskReductionScore]",
              "    VAR FlowName = ProcessConfiguration[FlowName]",
              "    VAR TotalRuns = CALCULATE(COUNTROWS(FlowRuns), CloudFlows[FlowName] = FlowName)",
              "    VAR SuccRuns = CALCULATE(COUNTROWS(FlowRuns), FlowRuns[StatusCategory] = \"Succeeded\", CloudFlows[FlowName] = FlowName)",
              "    RETURN RiskScore * DIVIDE(SuccRuns, TotalRuns, 0))",
              "VAR MaxScore = SUM(ProcessConfiguration[RiskReductionScore])",
              "RETURN DIVIDE(TotalScore, MaxScore, 0)"
            ],
            "formatString": "0.0%",
            "displayFolder": "Risk"
          },
          {
            "name": "Governance Score",
            "expression": [
              "VAR SolutionScore = [Solution Coverage] * 25",
              "VAR ProcessCoverage = DIVIDE(COUNTROWS(ProcessConfiguration), [Total Cloud Flows], 0)",
              "VAR ProcessScore = ProcessCoverage * 25",
              "VAR ReliabilityScore = [Success Rate] * 25",
              "VAR ActiveScore = [Active Flow Percentage] * 25",
              "RETURN ROUND(SolutionScore + ProcessScore + ReliabilityScore + ActiveScore, 0)"
            ],
            "formatString": "0",
            "displayFolder": "Governance"
          },
          {
            "name": "Governance Score Label",
            "expression": [
              "VAR Score = [Governance Score]",
              "RETURN IF(Score >= 90, \"Excellent\",",
              "    IF(Score >= 75, \"Good\",",
              "    IF(Score >= 60, \"Needs Improvement\",",
              "    IF(Score >= 40, \"At Risk\", \"Critical\"))))"
            ],
            "displayFolder": "Governance"
          },
          {
            "name": "Flows Per Owner",
            "expression": "DIVIDE([Total Cloud Flows], [Unique Flow Owners], 0)",
            "formatString": "0.0",
            "displayFolder": "Governance"
          },
          {
            "name": "Stale Flows",
            "expression": "CALCULATE(COUNTROWS(CloudFlows), CloudFlows[FlowState] = \"Activated\", FILTER(CloudFlows, DATEDIFF(CloudFlows[ModifiedOn], NOW(), DAY) > 90))",
            "displayFolder": "Governance"
          },
          {
            "name": "Runs YTD",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), DATESYTD(DateTable[Date]))",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Runs MTD",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), DATESMTD(DateTable[Date]))",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Runs Previous Month",
            "expression": "CALCULATE(COUNTROWS(FlowRuns), DATEADD(DateTable[Date], -1, MONTH))",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Runs MoM Change %",
            "expression": "VAR CurrentMonth = [Runs MTD]\nVAR PrevMonth = [Runs Previous Month]\nRETURN DIVIDE(CurrentMonth - PrevMonth, PrevMonth, 0)",
            "formatString": "0.0%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Flow Health Score",
            "expression": [
              "VAR SuccessRateScore = [Success Rate] * 40",
              "VAR NoTimeoutScore = (1 - DIVIDE([Timed Out Runs], [Total Flow Runs], 0)) * 20",
              "VAR AvgDuration = [Avg Run Duration (Minutes)]",
              "VAR DurationScore = IF(AvgDuration <= 1, 20, IF(AvgDuration <= 5, 15, IF(AvgDuration <= 15, 10, IF(AvgDuration <= 60, 5, 0))))",
              "RETURN MIN(ROUND(SuccessRateScore + NoTimeoutScore + DurationScore, 0), 100)"
            ],
            "formatString": "0",
            "displayFolder": "Governance"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = Table.FromRecords({[MeasureHelper = 1]}) in Source"
            }
          }
        ],
        "isHidden": true
      }
    ],
    "relationships": [
      {
        "name": "CloudFlows_FlowRuns",
        "fromTable": "FlowRuns",
        "fromColumn": "FlowID",
        "toTable": "CloudFlows",
        "toColumn": "FlowID",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "CloudFlows_SystemUsers",
        "fromTable": "CloudFlows",
        "fromColumn": "OwnerID",
        "toTable": "SystemUsers",
        "toColumn": "UserID"
      },
      {
        "name": "CloudFlows_ProcessConfig",
        "fromTable": "CloudFlows",
        "fromColumn": "FlowName",
        "toTable": "ProcessConfiguration",
        "toColumn": "FlowName"
      },
      {
        "name": "FlowRuns_DateTable",
        "fromTable": "FlowRuns",
        "fromColumn": "RunDate",
        "toTable": "DateTable",
        "toColumn": "Date"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DateTable\",\"SystemUsers\",\"CloudFlows\",\"FlowRuns\",\"ProcessConfiguration\"]"
      }
    ]
  }
}
